@LMSAPP.Server_HostAddress = https://localhost:7001/api

### Exemple de requête GET
GET {{LMSAPP.Server_HostAddress}}/users
Accept: application/json

### Exemple de requête POST
POST {{LMSAPP.Server_HostAddress}}/auth/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "password"
}

###
